### ISSUE TITLE
优化后构建效果的问题

### ISSUE THREAD

**Issue by weituotian** [qiudongwei/blog#10]
2.3. 优化后构建效果
说明：
a. 自定义chunk-vendor的打包策略，两个页面公共引用的代码块打包在chunk-common.js
b.spring_festival中的第三方库抽离为spring-festival-vendor.js，里面是关于vue-router的内容（可以根据需要决定是否抽离）。

只抽离vue-router？我有很多第三库呢

**Comment by lostvita** [comment]
我这个例子里面`spring-festival-vendor.js`是只抽离了`vue-router`，你有其他的第三方库需要抽离，在`splitChunks`里面定义抽离策略就好了（文章里面有介绍如何定义策略，或者你查看webpack文档）。

**Comment by weituotian** [comment]
@qiudongwei 请问有一劳永逸的方法吗？比如判断当前是属于views文件夹下哪个文件夹
因为现在的包实在太多了，全部一个一个添加很费时间

**Comment by mylhei** [comment]
没有看到dll和vue CLI3结合呢？
我本地遇到问题， 当有split分包时dll无法正常使用，博主可以实践下么？

**Comment by lostvita** [comment]
@mylhei 有的呢！你看下`vue-cli-project`这个项目，执行`npm run dll`会产出一个`dll`目录，`vendor.dll.js`里面打包了`vue.js`的代码；执行`npm run build`会产出`dist`目录，里面的`js`文件则不再包含`vue.js`代码。
![image](https://user-images.githubusercontent.com/26505680/59989634-8e56c480-9672-11e9-98d5-118eaa6f9276.png)

**Comment by lostvita** [comment]
@weituotian 你的场景是要为每一个page定义分离策略？还是page里面每增加一个第三方库就进行分离（打包在一个公告包）？
前者只能在配置文件里面一个个定义，后者的话设置下引用次数`minChunks: 2`应该就可以了。
